SET(BIN_DIR "${CMAKE_CURRENT_BINARY_DIR}/bin")
SET(LIB_DIR "${CMAKE_CURRENT_BINARY_DIR}/lib")

FILE(
  MAKE_DIRECTORY
  ${BIN_DIR}
  ${LIB_DIR}
  )

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BIN_DIR})
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CMAKE_BUILD_TYPE} ${BIN_DIR})
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${BIN_DIR})
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${BIN_DIR})

SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${LIB_DIR})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CMAKE_BUILD_TYPE} ${LIB_DIR})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${LIB_DIR})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${LIB_DIR})

SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${LIB_DIR})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CMAKE_BUILD_TYPE} ${LIB_DIR})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${LIB_DIR})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${LIB_DIR})
